### ISSUE TITLE
Ergonomics / Polish / Initial Experience "Punch List"

### ISSUE THREAD

**Issue by wycats** [glimmerjs/glimmer-application#58]
- [ ] Can't use `async function` out of the box due missing `regeneratorRuntime` (#55)
- [ ] Sourcemaps seem broken (#56)
- [ ] Integration with npm packages should be documented and/or improved (#57)
- [ ] Guides need a quick (optional) introduction to TypeScript and pointers to other resources. (glimmerjs/glimmer-website#65)
- [ ] Guides need to document args vs. attrs (and more generally, templates!) (glimmerjs/glimmer-website#66)
- [ ] Nested components are broken (https://github.com/glimmerjs/glimmer-application/issues/84)

This issue is not intended to supersede #54, which is largely focused on technical and internal issues.

**Comment by locks** [comment]
Added https://github.com/glimmerjs/glimmer-application/issues/84.

**Comment by locks** [comment]
Moved to https://github.com/glimmerjs/glimmer-application/projects/1.
